name: template-sync

on:
  # cronjob trigger
  #schedule:
  #  - cron:  "0 0 1 * *"
  # manual trigger
  workflow_dispatch:

env:
  SOURCE_BRANCH: main
  SOURCE_REPOSITORY: google/docsy-example

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        if: github.repository != env.SOURCE_REPOSITORY
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1.1.8
        if: github.repository != env.SOURCE_REPOSITORY
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          source_repo_path: ${{ env.SOURCE_REPOSITORY }}
          upstream_branch: ${{ env.SOURCE_BRANCH }}
          pr_title: "[actions-template-sync] Upstream template update"
          pr_commit_msg: "chore(template): upstream template update"
